import 'fake-indexeddb/auto';
import { afterEach,describe,it,expect } from 'vitest';
import { LocalDatabase,saveLocalOrder,flushQueue } from '../src/lib/local';
import { demoSnapshot } from '../src/lib/demo';
const dbs:LocalDatabase[]=[];
function setup(){const db=new LocalDatabase(crypto.randomUUID());dbs.push(db);const s=demoSnapshot();const order={...s.orders[0],version:0,payments:[]};const scope={userId:s.userId,tenantId:order.tenant_id,branchId:order.branch_id};return {db,order,scope};}
afterEach(async()=>{await Promise.all(dbs.splice(0).map(db=>db.delete()));});
describe('cola local',()=>{
 it('guarda orden y operación atómicamente y sobrevive a reinicio',async()=>{const {db,scope,order}=setup();await saveLocalOrder(scope,order,Date.now(),db);const name=db.name;db.close();const reopened=new LocalDatabase(name);dbs.push(reopened);expect(await reopened.orders.count()).toBe(1);expect(await reopened.operations.count()).toBe(1);});
 it('mantiene una petición inmutable si se pierde la respuesta y reintenta sin duplicar',async()=>{const {db,scope,order}=setup();await saveLocalOrder(scope,order,Date.now(),db);const seen=new Set();let applied=0;let disconnect=true;const send=async(op:any)=>{if(!seen.has(op.id)){seen.add(op.id);applied++;}if(disconnect){disconnect=false;throw new Error('network');}return {state:'applied' as const,order:{...op.order,version:op.baseVersion+1}};};await expect(flushQueue(scope,send,db)).rejects.toThrow('network');expect(await db.operations.count()).toBe(1);await flushQueue(scope,send,db);expect(applied).toBe(1);expect(await db.operations.count()).toBe(0);});
 it('encadena versiones y bloquea cambios posteriores tras conflicto',async()=>{const {db,scope,order}=setup();const next=await saveLocalOrder(scope,order,Date.now(),db);await saveLocalOrder(scope,{...next,notes:'segunda edición'},Date.now(),db);let sent=0;await flushQueue(scope,async()=>{sent++;return {state:'conflict',order:{...order,version:2},message:'Cambió'};},db);expect(sent).toBe(1);expect(await db.operations.count()).toBe(2);await expect(saveLocalOrder(scope,{...next,version:2},Date.now(),db)).rejects.toThrow('conflicto');});
 it('no envía operaciones de otro usuario o sede',async()=>{const {db,scope,order}=setup();await saveLocalOrder(scope,order,Date.now(),db);let calls=0;await flushQueue({...scope,userId:crypto.randomUUID()},async()=>{calls++;return {state:'applied',order};},db);expect(calls).toBe(0);expect(await db.operations.count()).toBe(1);});
 it('no pierde una edición posterior mientras se confirma la primera',async()=>{const {db,scope,order}=setup();const next=await saveLocalOrder(scope,order,Date.now(),db);await flushQueue(scope,async op=>{await saveLocalOrder(scope,{...next,notes:'nuevo'},Date.now(),db);return {state:'applied',order:{...op.order,version:1}};},db);expect((await db.orders.toArray())[0].order.notes).toBe('nuevo');expect(await db.operations.count()).toBe(1);});
 it('rechaza sesión vencida y actualización desde pestaña obsoleta',async()=>{const {db,scope,order}=setup();await expect(saveLocalOrder(scope,order,Date.now()-8*86400000,db)).rejects.toThrow('validar');await saveLocalOrder(scope,order,Date.now(),db);await expect(saveLocalOrder(scope,order,Date.now(),db)).rejects.toThrow('otra pestaña');});
});
