'use client';
import { useState } from 'react';
import { Plus, Trash2 } from 'lucide-react';
import { type Order, type Branch, type Worker, type CatalogItem, equalAllocations, total, cop, orderSchema } from '@/lib/domain';
import { nextFolio } from '@/lib/local';
import { Field } from './ui';
export function OrderEditor({existing,branch,workers,catalog,device,onSave}:{existing?:Order;branch:Branch;workers:Worker[];catalog:CatalogItem[];device:string;onSave:(o:Order)=>Promise<void>}) {
 const [plate,setPlate]=useState(existing?.plate??''),[vehicle,setVehicle]=useState(existing?.vehicle_type??'Automóvil'),[name,setName]=useState(existing?.customer_name??''),[phone,setPhone]=useState(existing?.customer_phone??''),[notes,setNotes]=useState(existing?.notes??''),[lines,setLines]=useState<Order['lines']>(existing?.lines??[]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState('');
 const available=catalog.filter(c=>c.active&&(c.kind==='product'||c.vehicle_type==='Todos'||c.vehicle_type===vehicle));
 const [reason,setReason]=useState('');
 const [paymentAmounts,setPaymentAmounts]=useState({cash:existing?.payments.filter(p=>p.method==='cash').reduce((n,p)=>n+p.amount,0)??0,transfer:existing?.payments.filter(p=>p.method==='transfer').reduce((n,p)=>n+p.amount,0)??0,card:existing?.payments.filter(p=>p.method==='card').reduce((n,p)=>n+p.amount,0)??0});
 function update(index:number,patch:Partial<Order['lines'][number]>){setLines(ls=>ls.map((l,i)=>i===index?{...l,...patch}:l));}
 return <form className="order-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{
  const order:Order=existing?{...existing,plate,vehicle_type:vehicle,customer_name:name,customer_phone:phone,notes,lines}:{id:crypto.randomUUID(),tenant_id:branch.tenant_id,branch_id:branch.id,device_id:device,folio:await nextFolio(branch.code,device),plate,vehicle_type:vehicle,customer_name:name,customer_phone:phone,notes,lines,payments:[],paid_at:null,cash_session_id:null,cancelled:false,reason:'',created_at:new Date().toISOString(),version:0,ticket:{name:branch.name,nit:branch.nit,address:branch.address,phone:branch.phone,footer:branch.footer,logo:branch.logo}};
  if(existing?.payments.length){order.reason=reason;order.payments=(['cash','transfer','card'] as const).filter(method=>paymentAmounts[method]>0).map(method=>({method,amount:paymentAmounts[method]}));if(!reason.trim())throw new Error('Indica el motivo de la corrección');if(!order.payments.length)throw new Error('Para retirar un pago, anula la orden con un motivo.');}
  const parsed=orderSchema.safeParse(order);if(!parsed.success)throw new Error(parsed.error.issues.map(i=>i.message).join('. '));await onSave(parsed.data);
 }catch(err){setError(err instanceof Error?err.message:'No se pudo guardar');}finally{setBusy(false);}}}>
  <div className="form-grid"><Field label="Placa del vehículo"><input autoFocus required value={plate} maxLength={12} placeholder="ABC 123" onChange={e=>setPlate(e.target.value.toUpperCase())}/></Field><Field label="Tipo de vehículo"><select value={vehicle} onChange={e=>setVehicle(e.target.value)}>{['Automóvil','Camioneta','Moto','Taxi','Otro'].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Nombre del cliente · opcional"><input value={name} maxLength={120} onChange={e=>setName(e.target.value)}/></Field><Field label="WhatsApp · opcional"><input value={phone} maxLength={25} type="tel" placeholder="57 300 000 0000" onChange={e=>setPhone(e.target.value)}/></Field></div>
  <div className="section-label">Servicios y productos</div><div className="add-line"><select value={selected} aria-label="Servicio o producto" onChange={e=>setSelected(e.target.value)}><option value="">Selecciona del catálogo…</option>{available.map(c=><option key={c.id} value={c.id}>{c.name} · {cop(c.price)}</option>)}</select><button type="button" onClick={()=>{const c=available.find(x=>x.id===selected);if(!c)return;setLines([...lines,{id:crypto.randomUUID(),catalog_id:c.id,name:c.name,kind:c.kind,quantity:1,price:Number(c.price),status:c.kind==='product'?'done':'pending',allocations:c.kind==='service'&&workers[0]?equalAllocations([workers[0]]):[]}]);setSelected('');}}><Plus size={16}/> Agregar</button></div>
  {lines.map((l,i)=><div className="line-editor" key={l.id}><div className="line-top"><strong>{l.name}</strong><span>{cop(l.price)}</span><input type="number" aria-label={`Cantidad ${l.name}`} min={1} max={1000} value={l.quantity} onChange={e=>update(i,{quantity:Number(e.target.value)})}/><button type="button" className="icon-button danger" aria-label={`Quitar ${l.name}`} onClick={()=>setLines(lines.filter((_,n)=>n!==i))}><Trash2 size={16}/></button></div>
  {l.kind==='service'&&<><div className="worker-options">{workers.filter(w=>w.active).map(w=><label key={w.id}><input type="checkbox" checked={l.allocations.some(a=>a.worker_id===w.id)} onChange={e=>{const ids=new Set(l.allocations.map(a=>a.worker_id));if(e.target.checked)ids.add(w.id);else ids.delete(w.id);update(i,{allocations:equalAllocations(workers.filter(x=>ids.has(x.id)))});}}/>{w.name.split(' ')[0]}</label>)}</div><div className="allocation-list">{l.allocations.map(a=><label key={a.worker_id}>{a.name}<span><input aria-label={`Porcentaje ${a.name}`} type="number" min="0.01" max="100" step="0.01" value={a.percent} onChange={e=>update(i,{allocations:l.allocations.map(x=>x.worker_id===a.worker_id?{...x,percent:Number(e.target.value)}:x)})}/>%</span></label>)}</div></>}
  </div>)}
  <Field label="Observaciones · opcional"><textarea value={notes} maxLength={2000} onChange={e=>setNotes(e.target.value)}/></Field>
  {Boolean(existing?.payments.length)&&<><p className="notice">Corrección administrativa. Ajusta el pago al nuevo total; la caja original debe seguir abierta.</p><div className="form-grid">{(['cash','transfer','card'] as const).map(method=><Field key={method} label={{cash:'Efectivo',transfer:'Transferencia',card:'Datáfono'}[method]}><input type="number" min={0} step="0.01" value={paymentAmounts[method]} onChange={e=>setPaymentAmounts({...paymentAmounts,[method]:Number(e.target.value)})}/></Field>)}</div><Field label="Motivo de la corrección"><textarea required value={reason} onChange={e=>setReason(e.target.value)}/></Field></>}
  <div className="order-total"><span>Total de la orden</span><strong>{cop(total({lines}))}</strong></div>{error&&<p className="error" role="alert">{error}</p>}<button className="primary full" disabled={busy}>{busy?'Guardando…':existing?'Guardar cambios':'Crear orden'}</button>
 </form>;
}
