'use client';
import { useEffect,useState } from 'react';
import { usePathname } from 'next/navigation';
import { LayoutDashboard,CarFront,Users,Package,Wallet,ChartNoAxesCombined,Settings,RefreshCw,Plus,ArrowRight,MoreHorizontal,Check,Clock,Wifi,WifiOff,LogOut,Building2,ShieldCheck,Menu,X,ReceiptText,Send,Leaf } from 'lucide-react';
import { useWorkspace } from '@/lib/use-workspace';
import { cop,total,status,day,financialSummary,canOperate,type Order } from '@/lib/domain';
import { serverAction } from '@/lib/api';
import { Login } from './login';
import { WaterLoader } from './water-loader';
import { Modal,RecordForm,Empty,type FieldSpec } from './ui';
import { OrderEditor } from './order-editor';
import { Receipt } from './receipt';
import { workspacePaths, workspaceTitles, viewFromPath, type WorkspaceView } from '@/lib/workspace-routes';
import { OverviewView } from './workspace-views/overview';
import { OrdersView } from './workspace-views/orders';
import { TeamView } from './workspace-views/team';
import { CatalogView } from './workspace-views/catalog';
import { CashView } from './workspace-views/cash';
import { ReportsView } from './workspace-views/reports';
import { SettingsView } from './workspace-views/settings';
import { SyncView } from './workspace-views/sync';
import { PlatformView } from './workspace-views/platform';
import { ClientsView } from './workspace-views/clients';
import { BusinessCustomersView } from './workspace-views/business-customers';
import { customerDirectory } from '@/lib/customers';
import type { WorkspaceViewModel } from './workspace-views/types';

const nav=[{id:'overview',label:'Vista general',icon:LayoutDashboard},{id:'orders',label:'Órdenes de servicio',icon:CarFront},{id:'customers',label:'Mis clientes',icon:Users},{id:'team',label:'Mi equipo',icon:Users},{id:'catalog',label:'Servicios y productos',icon:Package},{id:'cash',label:'Caja y gastos',icon:Wallet},{id:'reports',label:'Reportes',icon:ChartNoAxesCombined}] as const;
export function Workspace(){
 const pathname=usePathname();
 const view=viewFromPath(pathname);
 const w=useWorkspace(); const [mobile,setMobile]=useState(false),[search,setSearch]=useState(''),[filter,setFilter]=useState('Todas'),[editor,setEditor]=useState<Order|'new'|null>(null),[selected,setSelected]=useState<Order|null>(null),[receipt,setReceipt]=useState<Order|null>(null),[dialog,setDialog]=useState<{title:string;fields:FieldSpec[];save:(d:Record<string,string>)=>Promise<void>}|null>(null),[from,setFrom]=useState(day(new Date())),[to,setTo]=useState(day(new Date())),[reportBranch,setReportBranch]=useState('all'),[reportWorker,setReportWorker]=useState('all'),[reportService,setReportService]=useState('all'),[reportMethod,setReportMethod]=useState('all'),[entering,setEntering]=useState(false);
 const {snapshot:s,branch,branchId,tenant}=w;
 const platformOnly=s.platformAdmin;
 useEffect(()=>{if(!s.userId)return;const fallback=platformOnly?'platform':'overview';if(platformOnly?view!=='platform'&&view!=='clients':view==='platform'||view==='clients'||!w.manager&&['team','catalog','reports','settings'].includes(view)){window.history.replaceState(null,'',workspacePaths[fallback]);}},[s.userId,platformOnly,view,w.manager]);
 const branchOrders=s.orders.filter(o=>o.branch_id===branchId).sort((a,b)=>b.created_at.localeCompare(a.created_at));
 const today=branchOrders.filter(o=>day(o.created_at)===day(new Date()));
 const live=today.filter(o=>!o.cancelled);const sales=live.reduce((n,o)=>n+total(o),0);const collected=financialSummary(branchOrders,day(new Date()),day(new Date())).collected;
 const workers=s.workers.filter(x=>x.branch_id===branchId);const catalog=s.catalog.filter(x=>x.branch_id===branchId);
 const pending=w.operations.filter(o=>o.state==='pending').length;const conflicts=w.operations.filter(o=>o.state!=='pending');
 const selectedCurrent=selected?s.orders.find(o=>o.id===selected.id)??selected:null;
 const reportOrders=s.orders.filter(o=>o.tenant_id===branch?.tenant_id&&(reportBranch==='all'||o.branch_id===reportBranch)&&day(o.created_at)>=from&&day(o.created_at)<=to&&(reportWorker==='all'||o.lines.some(l=>l.allocations.some(a=>a.worker_id===reportWorker)))&&(reportService==='all'||o.lines.some(l=>l.catalog_id===reportService))&&(reportMethod==='all'||o.payments.some(p=>p.method===reportMethod)));
 const reportLive=reportOrders.filter(o=>!o.cancelled);const reportExpenses=s.expenses.filter(e=>e.tenant_id===branch?.tenant_id&&(reportBranch==='all'||e.branch_id===reportBranch)&&day(e.created_at)>=from&&day(e.created_at)<=to);
 const reportSales=reportLive.reduce((n,o)=>n+total(o),0),reportPaid=financialSummary(s.orders.filter(o=>o.tenant_id===branch?.tenant_id&&(reportBranch==='all'||o.branch_id===reportBranch)&&(reportWorker==='all'||o.lines.some(l=>l.allocations.some(a=>a.worker_id===reportWorker)))&&(reportService==='all'||o.lines.some(l=>l.catalog_id===reportService))&&(reportMethod==='all'||o.payments.some(p=>p.method===reportMethod))),from,to).collected,expenseTotal=reportExpenses.reduce((n,e)=>n+Number(e.amount),0);
 async function run(fn:()=>Promise<unknown>){try{await fn();}catch(e){w.setNotice(e instanceof Error?e.message:'No se pudo completar la acción');}}
 function form(title:string,fields:FieldSpec[],save:(d:Record<string,string>)=>Promise<void>){setDialog({title,fields,save:async d=>{await save(d);setDialog(null);}});}
 function pay(order:Order){if(!w.cash){w.setNotice('Abre tu caja antes de registrar el pago.');navigate('cash');return;}form(`Cobrar ${order.plate} · ${cop(total(order))}`,[{name:'cash',label:'Efectivo',type:'number',min:0,value:total(order)},{name:'transfer',label:'Transferencia',type:'number',min:0,value:0},{name:'card',label:'Datáfono',type:'number',min:0,value:0}],async d=>{const payments=(['cash','transfer','card'] as const).filter(m=>Number(d[m])>0).map(method=>({method,amount:Number(d[method])}));await w.saveOrder({...order,payments,paid_at:new Date().toISOString(),cash_session_id:w.cash!.id});});}
 async function share(order:Order){if(w.demo)throw new Error('WhatsApp con enlace requiere Supabase. Descarga el PDF para compartir la demostración.');if(w.operations.some(op=>op.orderId===order.id))throw new Error('Sincroniza esta orden antes de compartir.');const tab=window.open('about:blank','_blank');if(tab)tab.opener=null;try{const {token}=await w.action('receipt.create',{order_id:order.id});const url=`${window.location.origin}/recibo/${token}`;const phone=order.customer_phone.replace(/\D/g,'');const normalized=phone.length===10?`57${phone}`:phone;const text=`Hola${order.customer_name?` ${order.customer_name}`:''}, aquí está el comprobante de tu servicio en ${order.ticket.name}: ${url}`;const link=`https://wa.me/${normalized}?text=${encodeURIComponent(text)}`;if(tab)tab.location.href=link;else window.location.assign(link);}catch(error){tab?.close();throw error;}}
 async function enterDashboard(action:()=>Promise<void>){setEntering(true);try{await action();await new Promise(resolve=>setTimeout(resolve,700));}finally{setEntering(false);}}
 if(!w.ready)return <main className="loading"><div className="brand-mark">b.</div><p>Preparando tu espacio…</p></main>;
 if(!s.userId)return <><Login onLogin={()=>enterDashboard(w.load)} onDemo={()=>enterDashboard(w.startDemo)}/>{entering&&<WaterLoader/>}</>;
 function navigate(v:WorkspaceView){if(platformOnly&&v!=='platform'&&v!=='clients')return;window.history.pushState(null,'',workspacePaths[v]);setMobile(false);setSearch('');}
 function orderTable(orders:Order[],compact=false){return orders.length?<div className="table-scroll"><table><thead><tr><th>Vehículo</th><th>Servicio / responsable</th><th>Estado</th><th>Total</th><th>Pago</th><th/></tr></thead><tbody>{orders.map(o=><tr key={o.id} onClick={()=>setSelected(o)} tabIndex={0} onKeyDown={e=>{if(e.key==='Enter')setSelected(o);}}><td><div className="vehicle-cell"><div className="vehicle-icon"><CarFront size={21}/></div><div><strong className="plate">{o.plate}</strong><small>{o.vehicle_type} · {new Date(o.created_at).toLocaleTimeString('es-CO',{hour:'2-digit',minute:'2-digit',timeZone:'America/Bogota'})}</small></div></div></td><td><strong>{o.lines[0]?.name}{o.lines.length>1&&` +${o.lines.length-1}`}</strong><small>{[...new Set(o.lines.flatMap(l=>l.allocations.map(a=>a.name)))].join(', ')||'Venta de producto'}</small></td><td><span className={`badge ${status(o)==='Terminada'?'green':status(o)==='En proceso'?'blue':o.cancelled?'red':'amber'}`}>{status(o)==='Terminada'?<Check size={12}/>:<Clock size={12}/>} {status(o)}</span></td><td className="money">{cop(total(o))}</td><td><span className={`payment ${o.payments.length?'paid':''}`}>{o.cancelled?'Anulada':o.payments.length?'Pagado':'Por cobrar'}</span></td><td><button className="icon-button" aria-label={`Ver orden ${o.plate}`} onClick={e=>{e.stopPropagation();setSelected(o);}}><MoreHorizontal size={19}/></button></td></tr>)}</tbody></table></div>:<Empty title="Todo listo para el próximo auto" detail="Crea una orden y empieza a registrar los servicios de tu lavadero."/>;}
 const model={w,s,branch,branchId,branchOrders,today,live,sales,collected,workers,catalog,pending,filter,setFilter,search,setSearch,from,setFrom,to,setTo,reportBranch,setReportBranch,reportWorker,setReportWorker,reportService,setReportService,reportMethod,setReportMethod,reportOrders,reportLive,reportSales,reportPaid,expenseTotal,orderTable,navigate,form,run} satisfies WorkspaceViewModel;
 return <><div className="app-shell">
  {mobile&&<div className="sidebar-scrim" onClick={()=>setMobile(false)}/>}
  <aside className={`sidebar ${mobile?'mobile-open':''}`}><a className="brand" href="#" onClick={e=>{e.preventDefault();navigate(platformOnly?'platform':'overview');}}><div className="brand-mark">b.</div><span>brillo<span className="brand-dot">.</span></span></a><div className="workspace-label">ESPACIO DE TRABAJO</div><div className="tenant-chip"><div className="tenant-initial">{tenant?.name.charAt(0)??'B'}</div><div><strong>{tenant?.name??'Plataforma'}</strong><small>{w.demo?'Cuenta de demostración':'Gestión de lavaderos'}</small></div></div><nav>{platformOnly?<><button aria-label="Plataforma" onClick={()=>navigate('platform')} className={view==='platform'?'active':''}><ShieldCheck size={19}/> Plataforma</button><button aria-label="Clientes" onClick={()=>navigate('clients')} className={view==='clients'?'active':''}><Users size={19}/> Clientes</button></>:nav.filter(n=>w.manager||!['team','catalog','reports'].includes(n.id)).map(n=><button key={n.id} aria-label={n.label} onClick={()=>navigate(n.id)} className={view===n.id?'active':''}><n.icon size={19}/>{n.label}{n.id==='orders'&&<span className="nav-count">{branchOrders.filter(o=>!o.cancelled&&status(o)!=='Terminada').length}</span>}</button>)}</nav><div className="sidebar-bottom">{!platformOnly&&<><button className={view==='sync'?'active':''} onClick={()=>navigate('sync')}><RefreshCw size={18}/> Sincronización{conflicts.length>0&&<span className="nav-count">{conflicts.length}</span>}</button>{w.manager&&<button className={view==='settings'?'active':''} onClick={()=>navigate('settings')}><Settings size={18}/> Configuración</button>}</>}<div className="sidebar-note"><Leaf size={18}/><p>Menos papel.<br/><strong>Más brillo en tu negocio.</strong></p></div><button className="profile" onClick={()=>void w.logout()}><span className="avatar">{platformOnly||w.membership?.role==='owner'?'AD':'OP'}</span><span><strong>{platformOnly?'Administrador de plataforma':w.membership?.role==='owner'?'Administrador':'Mi cuenta'}</strong><small>{platformOnly?'Gestión de clientes':w.membership?.role==='owner'?'Dueño del negocio':'Operación'}</small></span><LogOut size={16}/></button></div></aside>
  <div className="main-shell"><header className="topbar"><div className="topbar-left"><button className="icon-button mobile-only" onClick={()=>setMobile(true)} aria-label="Abrir menú"><Menu size={22}/></button>{!platformOnly&&<><Building2 size={18}/><select aria-label="Sede activa" value={branchId} onChange={e=>w.setBranchId(e.target.value)}>{s.branches.map(b=><option key={b.id} value={b.id}>{b.name}{!b.active?' · inactiva':''}</option>)}</select><span className="topbar-divider"/></>}<span className="muted small">{platformOnly?view==='clients'?'Clientes':'Plataforma':view==='overview'?'Vista general':nav.find(n=>n.id===view)?.label??'Administración'}</span></div><div className="topbar-right">{!platformOnly&&<button className={`connection ${!w.online?'offline':''}`} onClick={()=>navigate('sync')}>{w.online?<Wifi size={15}/>:<WifiOff size={15}/>}<span>{w.online?pending?`${pending} pendientes`:'En línea':'Sin conexión'}</span></button>}<span className="avatar small-avatar">AD</span></div></header>
  {w.demo&&<div className="demo-banner"><span>Demostración local · datos de ejemplo, sin conexión a Supabase.</span><button onClick={()=>void w.logout()}>Salir de la demo <ArrowRight size={14}/></button></div>}
  {w.notice&&<div className="toast" role="status"><span>{w.notice}</span><button className="icon-button" onClick={()=>w.setNotice('')} aria-label="Cerrar aviso"><X size={16}/></button></div>}
  {!canOperate(s.validatedAt)&&<div className="warning">El acceso local venció. Conéctate e ingresa de nuevo para continuar; tus operaciones pendientes están conservadas.</div>}
  <main className="content"><div className="page-heading"><div><div className="eyebrow">{view==='overview'?new Date().toLocaleDateString('es-CO',{weekday:'long',day:'numeric',month:'long',timeZone:'America/Bogota'}):tenant?.name??'BRILLO'}</div><h1>{workspaceTitles[view]}</h1><p>{view==='overview'?'Un vistazo a lo que está pasando hoy en tu lavadero.':view==='orders'?'Del primer enjuague al último detalle.':view==='reports'?'Decisiones claras, con información de todas tus sedes.':view==='platform'?'Indicadores de suscripciones y actividad de tu plataforma.':view==='clients'?'Administra clientes, suscripciones y cobros registrados fuera de Brillo.':'Todo lo que necesitas para seguir creciendo.'}</p></div>{['overview','orders'].includes(view)&&<button className="primary heading-action" disabled={!branch?.active||!canOperate(s.validatedAt)} onClick={()=>setEditor('new')}><Plus size={18}/> Nueva orden</button>}</div>
  {!branch&&!s.platformAdmin&&<Empty title="Tu cuenta todavía no tiene sedes disponibles" detail="El dueño o administrador de plataforma debe habilitar tu acceso."/>}
  {!platformOnly&&<>
    {view==='overview'&&branch&&<OverviewView model={model}/>}
    {view==='orders'&&branch&&<OrdersView model={model}/>}
    {view==='team'&&w.manager&&<TeamView model={model}/>}
    {view==='customers'&&branch&&<BusinessCustomersView model={model}/>}
    {view==='catalog'&&w.manager&&<CatalogView model={model}/>}
    {view==='cash'&&branch&&<CashView model={model}/>}
    {view==='reports'&&w.manager&&<ReportsView model={model}/>}
    {view==='settings'&&w.manager&&<SettingsView model={model}/>}
    {view==='sync'&&<SyncView model={model}/>}
  </>}
  {view==='platform'&&s.platformAdmin&&<PlatformView model={model}/>}
  {view==='clients'&&s.platformAdmin&&<ClientsView model={model}/>}
  </main><footer className="app-footer"><span>brillo. <span>Tu lavadero, en orden.</span></span><span>Hecho para moverse contigo.</span></footer></div>
  {editor&&branch&&<Modal title={editor==='new'?'Nueva orden de servicio':`Editar ${editor.plate}`} wide onClose={()=>setEditor(null)}><OrderEditor existing={editor==='new'?undefined:editor} branch={branch} workers={workers.filter(w=>w.active)} catalog={catalog} directory={customerDirectory(s,branch.tenant_id)} device={w.device} onSave={async o=>{await w.saveOrder(o);setEditor(null);}}/></Modal>}
  {selectedCurrent&&<Modal title={`Orden · ${selectedCurrent.plate}`} wide onClose={()=>setSelected(null)}><div className="order-detail"><div className="detail-head"><div><small>{selectedCurrent.folio}</small><h3>{selectedCurrent.plate}</h3><p>{selectedCurrent.vehicle_type} · {selectedCurrent.customer_name||'Cliente ocasional'}</p></div><strong>{cop(total(selectedCurrent))}</strong></div>{selectedCurrent.lines.map((l,i)=><div className="detail-line" key={l.id}><div><strong>{l.name}</strong><small>{l.allocations.map(a=>`${a.name} (${a.percent}%)`).join(', ')}</small></div><span>{cop(l.price*l.quantity)}</span>{l.kind==='service'&&<select aria-label={`Estado ${l.name}`} value={l.status} disabled={selectedCurrent.cancelled} onChange={e=>void run(()=>w.saveOrder({...selectedCurrent,lines:selectedCurrent.lines.map((x,n)=>n===i?{...x,status:e.target.value as 'pending'|'working'|'done'}:x)}))}><option value="pending">Pendiente</option><option value="working">En proceso</option><option value="done">Terminado</option></select>}</div>)}{selectedCurrent.notes&&<p className="notice">{selectedCurrent.notes}</p>}<div className="row-actions wrap">{!selectedCurrent.payments.length&&!selectedCurrent.cancelled&&<button className="primary" onClick={()=>pay(selectedCurrent)}>Cobrar {cop(total(selectedCurrent))}</button>}{(!selectedCurrent.payments.length||w.manager)&&!selectedCurrent.cancelled&&<button onClick={()=>{setEditor(selectedCurrent);setSelected(null);}}>{selectedCurrent.payments.length?'Corregir orden':'Editar orden'}</button>}<button onClick={()=>{setReceipt(selectedCurrent);setSelected(null);}}><ReceiptText size={16}/> Ver boleta</button><button onClick={()=>void run(()=>share(selectedCurrent))}><Send size={16}/> WhatsApp</button><button onClick={()=>void run(()=>w.action('receipt.revoke',{order_id:selectedCurrent.id}))}>Revocar enlaces</button>{w.manager&&!selectedCurrent.cancelled&&<button className="danger" onClick={()=>form('Anular orden',[{name:'reason',label:'Motivo de anulación',type:'textarea'}],async d=>{await w.saveOrder({...selectedCurrent,cancelled:true,reason:d.reason});setSelected(null);})}>Anular</button>}</div></div></Modal>}
  {receipt&&<Modal title="Boleta de servicio" onClose={()=>setReceipt(null)}><Receipt order={receipt}/></Modal>}
  {dialog&&<Modal title={dialog.title} onClose={()=>setDialog(null)}><RecordForm fields={dialog.fields} onSubmit={dialog.save}/></Modal>}
 </div>{entering&&<WaterLoader/>}</>;
}
