'use client';
import { useState,type ReactNode } from 'react';
import { LayoutDashboard,CarFront,Users,Package,Wallet,ChartNoAxesCombined,Settings,RefreshCw,Plus,Search,ArrowUpRight,ArrowRight,MoreHorizontal,Check,Clock,Wifi,WifiOff,LogOut,ChevronDown,Download,Building2,ShieldCheck,Menu,X,ReceiptText,TriangleAlert,CheckCheck,Send,Leaf } from 'lucide-react';
import { useWorkspace } from '@/lib/use-workspace';
import { cop,total,status,day,productivity,csv,financialSummary,scopeKey,canOperate,type Order,type CatalogItem,type Worker,type Branch } from '@/lib/domain';
import { supabase } from '@/lib/supabase';
import { serverAction } from '@/lib/api';
import { dismissLocal,localOrders,local } from '@/lib/local';
import { downloadText } from '@/lib/receipt';
import { Login } from './login';
import { Modal,RecordForm,Empty,Field,type FieldSpec } from './ui';
import { OrderEditor } from './order-editor';
import { Receipt } from './receipt';
import { SyncCenter } from './sync-center';

type View='overview'|'orders'|'team'|'catalog'|'cash'|'reports'|'settings'|'sync'|'platform';
const nav=[{id:'overview',label:'Vista general',icon:LayoutDashboard},{id:'orders',label:'Órdenes de servicio',icon:CarFront},{id:'team',label:'Mi equipo',icon:Users},{id:'catalog',label:'Servicios y productos',icon:Package},{id:'cash',label:'Caja y gastos',icon:Wallet},{id:'reports',label:'Reportes',icon:ChartNoAxesCombined}] as const;
const viewTitles:Record<View,string>={overview:'Todo en orden.',orders:'Órdenes de servicio',team:'El equipo que hace la diferencia',catalog:'Servicios y productos',cash:'Cada peso, en su lugar',reports:'Los números de tu negocio',settings:'Tu negocio, a tu manera',sync:'Centro de sincronización',platform:'Administración de clientes'};
export function Workspace(){
 const w=useWorkspace(); const [view,setView]=useState<View>('overview'),[mobile,setMobile]=useState(false),[search,setSearch]=useState(''),[filter,setFilter]=useState('Todas'),[editor,setEditor]=useState<Order|'new'|null>(null),[selected,setSelected]=useState<Order|null>(null),[receipt,setReceipt]=useState<Order|null>(null),[dialog,setDialog]=useState<{title:string;fields:FieldSpec[];save:(d:Record<string,string>)=>Promise<void>}|null>(null),[from,setFrom]=useState(day(new Date())),[to,setTo]=useState(day(new Date())),[reportBranch,setReportBranch]=useState('all'),[reportWorker,setReportWorker]=useState('all'),[reportService,setReportService]=useState('all'),[reportMethod,setReportMethod]=useState('all');
 const {snapshot:s,branch,branchId,tenant}=w;
 const branchOrders=s.orders.filter(o=>o.branch_id===branchId).sort((a,b)=>b.created_at.localeCompare(a.created_at));
 const today=branchOrders.filter(o=>day(o.created_at)===day(new Date()));
 const live=today.filter(o=>!o.cancelled);const sales=live.reduce((n,o)=>n+total(o),0);const collected=financialSummary(branchOrders,day(new Date()),day(new Date())).collected;
 const workers=s.workers.filter(x=>x.branch_id===branchId);const catalog=s.catalog.filter(x=>x.branch_id===branchId);
 const pending=w.operations.filter(o=>o.state==='pending').length;const conflicts=w.operations.filter(o=>o.state!=='pending');
 const selectedCurrent=selected?s.orders.find(o=>o.id===selected.id)??selected:null;
 const reportOrders=s.orders.filter(o=>o.tenant_id===branch?.tenant_id&&(reportBranch==='all'||o.branch_id===reportBranch)&&day(o.created_at)>=from&&day(o.created_at)<=to&&(reportWorker==='all'||o.lines.some(l=>l.allocations.some(a=>a.worker_id===reportWorker)))&&(reportService==='all'||o.lines.some(l=>l.catalog_id===reportService))&&(reportMethod==='all'||o.payments.some(p=>p.method===reportMethod)));
 const reportLive=reportOrders.filter(o=>!o.cancelled);const reportExpenses=s.expenses.filter(e=>e.tenant_id===branch?.tenant_id&&(reportBranch==='all'||e.branch_id===reportBranch)&&day(e.created_at)>=from&&day(e.created_at)<=to);
 const reportSales=reportLive.reduce((n,o)=>n+total(o),0),reportPaid=financialSummary(s.orders.filter(o=>o.tenant_id===branch?.tenant_id&&(reportBranch==='all'||o.branch_id===reportBranch)&&(reportWorker==='all'||o.lines.some(l=>l.allocations.some(a=>a.worker_id===reportWorker)))&&(reportService==='all'||o.lines.some(l=>l.catalog_id===reportService))&&(reportMethod==='all'||o.payments.some(p=>p.method===reportMethod))),from,to).collected,expenseTotal=reportExpenses.reduce((n,e)=>n+Number(e.amount),0);
 async function run(fn:()=>Promise<unknown>){try{await fn();}catch(e){w.setNotice(e instanceof Error?e.message:'No se pudo completar la acción');}}
 function form(title:string,fields:FieldSpec[],save:(d:Record<string,string>)=>Promise<void>){setDialog({title,fields,save:async d=>{await save(d);setDialog(null);}});}
 function workerForm(worker?:Worker){form(worker?'Editar trabajador':'Agregar trabajador',[{name:'name',label:'Nombre completo',value:worker?.name},{name:'active',label:'Estado',value:String(worker?.active??true),options:[{value:'true',label:'Activo'},{value:'false',label:'Inactivo'}]}],async d=>{await w.action('worker.save',{id:worker?.id??d._request_id,...d,active:d.active==='true'});});}
 function catalogForm(item?:CatalogItem){form(item?'Editar catálogo':'Nuevo servicio o producto',[{name:'name',label:'Nombre',value:item?.name},{name:'kind',label:'Tipo',value:item?.kind??'service',options:[{value:'service',label:'Servicio'},{value:'product',label:'Producto / insumo'}]},{name:'vehicle_type',label:'Vehículo',value:item?.vehicle_type??'Todos',options:['Todos','Automóvil','Camioneta','Moto','Taxi','Otro'].map(v=>({value:v,label:v}))},{name:'price',label:'Precio de venta (COP)',type:'number',min:0,value:item?.price??0},{name:'minimum_stock',label:'Existencia mínima (productos)',type:'number',min:0,value:item?.minimum_stock??0},{name:'active',label:'Estado',value:String(item?.active??true),options:[{value:'true',label:'Activo'},{value:'false',label:'Inactivo'}]}],async d=>{await w.action('catalog.save',{...d,id:item?.id??d._request_id,price:Number(d.price),minimum_stock:Number(d.minimum_stock),active:d.active==='true'});});}
 function moveStock(item:CatalogItem){form(`Movimiento · ${item.name}`,[{name:'quantity',label:'Cantidad (+ entrada / − consumo o desperdicio)',type:'number',step:'0.001'},{name:'reason',label:'Motivo del movimiento'}],async d=>{if(!Number(d.quantity))throw new Error('La cantidad debe ser distinta de cero');await w.action('inventory.move',{id:d._request_id,product_id:item.id,quantity:Number(d.quantity),reason:d.reason});});}
 function pay(order:Order){if(!w.cash){w.setNotice('Abre tu caja antes de registrar el pago.');setView('cash');return;}form(`Cobrar ${order.plate} · ${cop(total(order))}`,[{name:'cash',label:'Efectivo',type:'number',min:0,value:total(order)},{name:'transfer',label:'Transferencia',type:'number',min:0,value:0},{name:'card',label:'Datáfono',type:'number',min:0,value:0}],async d=>{const payments=(['cash','transfer','card'] as const).filter(m=>Number(d[m])>0).map(method=>({method,amount:Number(d[method])}));await w.saveOrder({...order,payments,paid_at:new Date().toISOString(),cash_session_id:w.cash!.id});});}
 function branchForm(b?:Branch){form(b?'Personalizar sede':'Nueva sede',[{name:'name',label:'Nombre en la boleta',value:b?.name},{name:'code',label:'Código (2–10 letras o números)',value:b?.code},{name:'nit',label:'NIT',value:b?.nit,required:false},{name:'address',label:'Dirección',value:b?.address,required:false},{name:'phone',label:'Teléfono',value:b?.phone,required:false},{name:'footer',label:'Mensaje al pie del ticket',value:b?.footer??'Gracias por confiar en nosotros.',required:false},{name:'active',label:'Estado',value:String(b?.active??true),options:[{value:'true',label:'Activa'},{value:'false',label:'Inactiva'}]}],async d=>{if(!/^[A-Z0-9]{2,10}$/.test(d.code))throw new Error('Usa 2–10 letras mayúsculas o números');await w.action('branch.save',{...d,id:b?.id??d._request_id,logo:b?.logo??'',active:d.active==='true'});});}
 function invite(){form('Invitar usuario',[{name:'email',label:'Correo electrónico',type:'email'},{name:'role',label:'Rol',options:[{value:'cashier',label:'Cajero de esta sede'},{value:'manager',label:'Administrador de esta sede'},{value:'owner',label:'Dueño · todas las sedes'}]}],async d=>{if(w.demo)throw new Error('Las invitaciones requieren configurar Supabase.');await serverAction('/api/invitations',{...d,tenant_id:branch?.tenant_id,branch_id:d.role==='owner'?null:branchId});w.setNotice('Invitación enviada.');});}
 async function logo(file:File){if(!branch)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>2*1024*1024)throw new Error('Usa PNG, JPG o WebP de hasta 2 MB.');const bitmap=await createImageBitmap(file);const canvas=document.createElement('canvas');canvas.width=256;canvas.height=256;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#fff';ctx.fillRect(0,0,256,256);const scale=Math.min(256/bitmap.width,256/bitmap.height);ctx.drawImage(bitmap,(256-bitmap.width*scale)/2,(256-bitmap.height*scale)/2,bitmap.width*scale,bitmap.height*scale);bitmap.close();const image=canvas.toDataURL('image/png');if(!w.demo){const {error}=await supabase().storage.from('business-assets').upload(`${branch.tenant_id}/${branch.id}/${crypto.randomUUID()}.png`,await (await fetch(image)).blob(),{contentType:'image/png',upsert:false});if(error)throw error;}await w.action('branch.save',{...branch,logo:image});}
 async function share(order:Order){if(w.demo)throw new Error('WhatsApp con enlace requiere Supabase. Descarga el PDF para compartir la demostración.');if(w.operations.some(op=>op.orderId===order.id))throw new Error('Sincroniza esta orden antes de compartir.');const tab=window.open('about:blank','_blank');if(tab)tab.opener=null;try{const {token}=await w.action('receipt.create',{order_id:order.id});const url=`${window.location.origin}/recibo/${token}`;const phone=order.customer_phone.replace(/\D/g,'');const normalized=phone.length===10?`57${phone}`:phone;const text=`Hola${order.customer_name?` ${order.customer_name}`:''}, aquí está el comprobante de tu servicio en ${order.ticket.name}: ${url}`;const link=`https://wa.me/${normalized}?text=${encodeURIComponent(text)}`;if(tab)tab.location.href=link;else window.location.assign(link);}catch(error){tab?.close();throw error;}}
 function exportReport(){downloadText(`reporte-${from}-${to}.csv`,csv([['Boleta','Fecha Colombia','Sede','Placa','Estado','Venta COP','Cobrado COP'],...reportOrders.map(o=>[o.folio,day(o.created_at),s.branches.find(b=>b.id===o.branch_id)?.name??'',o.plate,status(o),o.cancelled?0:total(o),o.cancelled?0:o.payments.reduce((n,p)=>n+p.amount,0)])]));}
 if(!w.ready)return <main className="loading"><div className="brand-mark">b.</div><p>Preparando tu espacio…</p></main>;
 if(!s.userId)return <Login onLogin={()=>void w.load()} onDemo={()=>void w.startDemo()}/>;
 function navigate(v:View){setView(v);setMobile(false);setSearch('');}
 function orderTable(orders:Order[],compact=false){return orders.length?<div className="table-scroll"><table><thead><tr><th>Vehículo</th><th>Servicio / responsable</th><th>Estado</th><th>Total</th><th>Pago</th><th/></tr></thead><tbody>{orders.map(o=><tr key={o.id} onClick={()=>setSelected(o)} tabIndex={0} onKeyDown={e=>{if(e.key==='Enter')setSelected(o);}}><td><div className="vehicle-cell"><div className="vehicle-icon"><CarFront size={21}/></div><div><strong className="plate">{o.plate}</strong><small>{o.vehicle_type} · {new Date(o.created_at).toLocaleTimeString('es-CO',{hour:'2-digit',minute:'2-digit',timeZone:'America/Bogota'})}</small></div></div></td><td><strong>{o.lines[0]?.name}{o.lines.length>1&&` +${o.lines.length-1}`}</strong><small>{[...new Set(o.lines.flatMap(l=>l.allocations.map(a=>a.name)))].join(', ')||'Venta de producto'}</small></td><td><span className={`badge ${status(o)==='Terminada'?'green':status(o)==='En proceso'?'blue':o.cancelled?'red':'amber'}`}>{status(o)==='Terminada'?<Check size={12}/>:<Clock size={12}/>} {status(o)}</span></td><td className="money">{cop(total(o))}</td><td><span className={`payment ${o.payments.length?'paid':''}`}>{o.cancelled?'Anulada':o.payments.length?'Pagado':'Por cobrar'}</span></td><td><button className="icon-button" aria-label={`Ver orden ${o.plate}`} onClick={e=>{e.stopPropagation();setSelected(o);}}><MoreHorizontal size={19}/></button></td></tr>)}</tbody></table></div>:<Empty title="Todo listo para el próximo auto" detail="Crea una orden y empieza a registrar los servicios de tu lavadero."/>;}
 const toolbar=<><div className="searchbox"><Search size={17}/><input placeholder="Buscar placa o cliente…" aria-label="Buscar órdenes" value={search} onChange={e=>setSearch(e.target.value)}/></div><button className="primary" disabled={!branch?.active||!canOperate(s.validatedAt)} onClick={()=>setEditor('new')}><Plus size={18}/> Nueva orden</button></>;
 return <div className="app-shell">
  {mobile&&<div className="sidebar-scrim" onClick={()=>setMobile(false)}/>}
  <aside className={`sidebar ${mobile?'mobile-open':''}`}><a className="brand" href="#" onClick={e=>{e.preventDefault();navigate('overview');}}><div className="brand-mark">b.</div><span>brillo<span className="brand-dot">.</span></span></a><div className="workspace-label">ESPACIO DE TRABAJO</div><div className="tenant-chip"><div className="tenant-initial">{tenant?.name.charAt(0)??'B'}</div><div><strong>{tenant?.name??'Plataforma'}</strong><small>{w.demo?'Cuenta de demostración':'Gestión de lavaderos'}</small></div></div><nav>{nav.filter(n=>w.manager||!['team','catalog','reports'].includes(n.id)).map(n=><button key={n.id} aria-label={n.label} onClick={()=>navigate(n.id)} className={view===n.id?'active':''}><n.icon size={19}/>{n.label}{n.id==='orders'&&<span className="nav-count">{branchOrders.filter(o=>!o.cancelled&&status(o)!=='Terminada').length}</span>}</button>)}</nav><div className="sidebar-bottom"><button className={view==='sync'?'active':''} onClick={()=>navigate('sync')}><RefreshCw size={18}/> Sincronización{conflicts.length>0&&<span className="nav-count">{conflicts.length}</span>}</button>{w.manager&&<button className={view==='settings'?'active':''} onClick={()=>navigate('settings')}><Settings size={18}/> Configuración</button>}{s.platformAdmin&&<button onClick={()=>navigate('platform')}><ShieldCheck size={18}/> Plataforma</button>}<div className="sidebar-note"><Leaf size={18}/><p>Menos papel.<br/><strong>Más brillo en tu negocio.</strong></p></div><button className="profile" onClick={()=>void w.logout()}><span className="avatar">{w.membership?.role==='owner'?'AD':'OP'}</span><span><strong>{w.membership?.role==='owner'?'Administrador':'Mi cuenta'}</strong><small>{w.membership?.role==='owner'?'Dueño del negocio':'Operación'}</small></span><LogOut size={16}/></button></div></aside>
  <div className="main-shell"><header className="topbar"><div className="topbar-left"><button className="icon-button mobile-only" onClick={()=>setMobile(true)} aria-label="Abrir menú"><Menu size={22}/></button><Building2 size={18}/><select aria-label="Sede activa" value={branchId} onChange={e=>w.setBranchId(e.target.value)}>{s.branches.map(b=><option key={b.id} value={b.id}>{b.name}{!b.active?' · inactiva':''}</option>)}</select><span className="topbar-divider"/><span className="muted small">{view==='overview'?'Vista general':nav.find(n=>n.id===view)?.label??'Administración'}</span></div><div className="topbar-right"><button className={`connection ${!w.online?'offline':''}`} onClick={()=>navigate('sync')}>{w.online?<Wifi size={15}/>:<WifiOff size={15}/>}<span>{w.online?pending?`${pending} pendientes`:'En línea':'Sin conexión'}</span></button><span className="avatar small-avatar">AD</span></div></header>
  {w.demo&&<div className="demo-banner"><span>Demostración local · datos de ejemplo, sin conexión a Supabase.</span><button onClick={()=>void w.logout()}>Salir de la demo <ArrowRight size={14}/></button></div>}
  {w.notice&&<div className="toast" role="status"><span>{w.notice}</span><button className="icon-button" onClick={()=>w.setNotice('')} aria-label="Cerrar aviso"><X size={16}/></button></div>}
  {!canOperate(s.validatedAt)&&<div className="warning">El acceso local venció. Conéctate e ingresa de nuevo para continuar; tus operaciones pendientes están conservadas.</div>}
  <main className="content"><div className="page-heading"><div><div className="eyebrow">{view==='overview'?new Date().toLocaleDateString('es-CO',{weekday:'long',day:'numeric',month:'long',timeZone:'America/Bogota'}):tenant?.name??'BRILLO'}</div><h1>{viewTitles[view]}</h1><p>{view==='overview'?'Un vistazo a lo que está pasando hoy en tu lavadero.':view==='orders'?'Del primer enjuague al último detalle.':view==='reports'?'Decisiones claras, con información de todas tus sedes.':'Todo lo que necesitas para seguir creciendo.'}</p></div>{['overview','orders'].includes(view)&&<button className="primary heading-action" disabled={!branch?.active||!canOperate(s.validatedAt)} onClick={()=>setEditor('new')}><Plus size={18}/> Nueva orden</button>}</div>
  {!branch&&!s.platformAdmin&&<Empty title="Tu cuenta todavía no tiene sedes disponibles" detail="El dueño o administrador de plataforma debe habilitar tu acceso."/>}
  {view==='overview'&&branch&&<>
   <div className="metric-grid"><Metric label="Ventas de hoy" value={cop(sales)} detail={`${live.length} órdenes registradas`} icon={<Wallet size={19}/>} accent/><Metric label="Vehículos atendidos" value={String(live.length).padStart(2,'0')} detail={`${live.filter(o=>status(o)==='Terminada').length} servicios terminados`} icon={<CarFront size={19}/>}/><Metric label="En el lavadero" value={String(live.filter(o=>status(o)!=='Terminada').length).padStart(2,'0')} detail="Órdenes pendientes y en proceso" icon={<Clock size={19}/>}/><Metric label="Por cobrar" value={cop(live.filter(o=>!o.payments.length).reduce((n,o)=>n+total(o),0))} detail={`${live.filter(o=>!o.payments.length).length} órdenes sin pago`} icon={<ReceiptText size={19}/>}/></div>
   <div className="overview-grid"><section className="panel activity-panel"><div className="panel-heading"><div><h2>Así va tu día</h2><p>Órdenes registradas por hora</p></div><span className="badge neutral">Hoy <ChevronDown size={12}/></span></div><div className="chart">{Array.from({length:12},(_,i)=>{const hour=i+7;const count=today.filter(o=>Number(new Intl.DateTimeFormat('en-GB',{timeZone:'America/Bogota',hour:'2-digit',hourCycle:'h23'}).format(new Date(o.created_at)))===hour).length;return <div className="chart-column" key={hour}><div className="bar-track"><div className={`bar ${count?'filled':''}`} style={{height:count?`${Math.max(15,Math.min(100,count*30))}%`:'3px'}}><span>{count||''}</span></div></div><small>{hour%12||12}{hour<12?'a':'p'}</small></div>;})}</div><div className="chart-footer"><span><i/> Órdenes de servicio</span><strong>{cop(collected)} <small>recaudados hoy</small></strong></div></section>
   <section className="panel team-panel"><div className="panel-heading"><div><h2>Tu equipo hoy</h2><p>El brillo es un trabajo en equipo</p></div><Users size={19}/></div>{workers.filter(x=>x.active).slice(0,4).map((worker,i)=>{const count=live.filter(o=>o.lines.some(l=>l.allocations.some(a=>a.worker_id===worker.id))).length;return <div className="team-row" key={worker.id}><span className={`avatar avatar-${i%3}`}>{worker.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><div><strong>{worker.name}</strong><small>{count} {count===1?'orden asignada':'órdenes asignadas'}</small></div><span className="active-dot"/></div>;})}{!workers.length&&<p className="muted">Agrega los trabajadores de esta sede.</p>}{w.manager&&<button className="text-button team-link" onClick={()=>navigate('team')}>Ver todo el equipo <ArrowRight size={15}/></button>}</section></div>
   <section className="panel"><div className="panel-heading"><div><h2>Órdenes recientes <span className="count-chip">{today.length}</span></h2><p>Los últimos vehículos que pasaron por aquí</p></div><button className="text-button" onClick={()=>navigate('orders')}>Ver todas <ArrowUpRight size={16}/></button></div>{orderTable(today.slice(0,5),true)}</section>
   <div className="bottom-note"><ShieldCheck size={15}/> {pending?`${pending} operaciones guardadas en este dispositivo, pendientes de sincronizar.`:w.demo?'Estás explorando datos de ejemplo.':'Los dispositivos sin conexión pueden tener registros aún no enviados.'}<span>{w.lastSync?`Actualizado ${new Date(w.lastSync).toLocaleTimeString('es-CO',{hour:'2-digit',minute:'2-digit'})}`:''}</span></div>
  </>}
  {view==='orders'&&branch&&<section className="panel"><div className="list-toolbar"><div className="tabs">{['Todas','Pendiente','En proceso','Terminada','Por cobrar'].map(f=><button className={filter===f?'selected':''} key={f} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="searchbox"><Search size={17}/><input value={search} aria-label="Buscar órdenes" onChange={e=>setSearch(e.target.value)} placeholder="Placa, cliente o boleta…"/></div></div>{orderTable(branchOrders.filter(o=>(filter==='Todas'||filter==='Por cobrar'&&!o.payments.length&&!o.cancelled||status(o)===filter)&&`${o.plate} ${o.customer_name} ${o.folio}`.toLowerCase().includes(search.toLowerCase())))}</section>}
  {view==='team'&&w.manager&&<><div className="section-toolbar"><p className="muted">Trabajadores de {branch?.name}. No necesitan una cuenta para recibir servicios.</p><button className="primary" onClick={()=>workerForm()}><Plus size={17}/> Agregar trabajador</button></div><div className="people-grid">{workers.map((worker,i)=>{const p=productivity(live).find(p=>p.name===worker.name);return <section className="panel person-card" key={worker.id}><div className={`avatar big-avatar avatar-${i%3}`}>{worker.name.split(' ').map(n=>n[0]).slice(0,2).join('')}</div><span className={`badge ${worker.active?'green':'neutral'}`}>{worker.active?'Activo':'Inactivo'}</span><h2>{worker.name}</h2><p>Equipo de {branch?.name}</p><div className="person-stats"><div><strong>{(p?.services??0).toFixed(1)}</strong><small>Servicios hoy</small></div><div><strong>{cop(p?.value??0)}</strong><small>Valor atribuido</small></div></div><button className="full" onClick={()=>workerForm(worker)}>Editar trabajador</button></section>;})}</div>{!workers.length&&<Empty title="Construye tu equipo" detail="Agrega al primer trabajador para poder asignarle servicios."/>}</>}
  {view==='catalog'&&w.manager&&<><div className="section-toolbar"><p className="muted">Precios e inventario exclusivos de esta sede.</p><button className="primary" onClick={()=>catalogForm()}><Plus size={17}/> Agregar al catálogo</button></div><section className="panel table-scroll"><table><thead><tr><th>Nombre</th><th>Tipo</th><th>Vehículo</th><th>Precio</th><th>Existencias</th><th>Acciones</th></tr></thead><tbody>{catalog.map(c=><tr key={c.id}><td><strong>{c.name}</strong><small>{c.active?'Activo':'Inactivo'}</small></td><td>{c.kind==='service'?'Servicio':'Producto / insumo'}</td><td>{c.vehicle_type}</td><td>{cop(Number(c.price))}</td><td>{c.kind==='product'?<span className={`badge ${Number(c.stock)<=Number(c.minimum_stock)?'amber':'green'}`}>{c.stock} {Number(c.stock)<=Number(c.minimum_stock)&&'· bajo'}</span>:'—'}</td><td><div className="row-actions"><button onClick={()=>catalogForm(c)}>Editar</button>{c.kind==='product'&&<button onClick={()=>moveStock(c)}>Movimiento</button>}</div></td></tr>)}</tbody></table>{!catalog.length&&<Empty title="Tu catálogo empieza aquí" detail="Agrega servicios y productos para empezar a recibir vehículos."/>}</section><section className="panel space-top"><div className="panel-heading"><h2>Últimos movimientos de inventario</h2></div><div className="table-scroll"><table><thead><tr><th>Fecha</th><th>Producto</th><th>Cantidad</th><th>Motivo</th></tr></thead><tbody>{s.movements.filter(m=>m.branch_id===branchId).slice(-30).reverse().map(m=><tr key={m.id}><td>{day(m.created_at)}</td><td>{catalog.find(c=>c.id===m.product_id)?.name}</td><td>{m.quantity}</td><td>{m.reason}</td></tr>)}</tbody></table></div></section></>}
  {view==='cash'&&branch&&<>
   <div className="metric-grid three"><Metric label="Tu caja" value={w.cash?'Abierta':'Cerrada'} detail={w.cash?`Base ${cop(Number(w.cash.opening))}`:'Abre una caja para comenzar a cobrar'} icon={<Wallet size={19}/>} accent/><Metric label="Cobrado hoy" value={cop(collected)} detail="Todos los medios de pago" icon={<CheckCheck size={19}/>}/><Metric label="Gastos de hoy" value={cop(s.expenses.filter(e=>e.branch_id===branchId&&day(e.created_at)===day(new Date())).reduce((n,e)=>n+Number(e.amount),0))} detail="Gastos registrados de la sede" icon={<ReceiptText size={19}/>}/></div>
   <div className="section-toolbar"><p className="muted">Caja por operador y dispositivo. Los cierres requieren sincronizar primero.</p><div className="row-actions">{w.manager&&<button onClick={()=>form('Registrar gasto',[{name:'amount',label:'Valor (COP)',type:'number',min:0.01},{name:'category',label:'Categoría',options:['Insumos','Servicios públicos','Mantenimiento','Arriendo','Otros'].map(v=>({value:v,label:v}))},{name:'description',label:'Descripción'},{name:'method',label:'Medio de pago',options:[{value:'cash',label:'Efectivo de tu caja'},{value:'transfer',label:'Transferencia'},{value:'card',label:'Datáfono'}]}],async d=>{await w.action('expense.add',{...d,id:d._request_id,amount:Number(d.amount),cash_session_id:d.method==='cash'?w.cash?.id??null:null});})}>Registrar gasto</button>}{w.cash?<button className="primary" onClick={()=>form('Cerrar caja',[{name:'counted',label:'Efectivo contado (COP)',type:'number',min:0}],async d=>{if(w.operations.some(o=>o.scope===scopeKey(w.scope)))throw new Error('Sincroniza y resuelve los pendientes antes de cerrar caja');await w.action('cash.close',{id:w.cash!.id,counted:Number(d.counted)});})}>Cerrar caja</button>:<button className="primary" onClick={()=>form('Abrir caja',[{name:'opening',label:'Base inicial en efectivo (COP)',type:'number',value:0,min:0}],async d=>{await w.action('cash.open',{id:d._request_id,device_id:w.device,opening:Number(d.opening)});})}>Abrir caja</button>}</div></div>
   <section className="panel"><div className="panel-heading"><h2>Historial de cajas</h2></div><div className="table-scroll"><table><thead><tr><th>Apertura</th><th>Base</th><th>Estado</th><th>Esperado</th><th>Contado</th><th>Diferencia</th></tr></thead><tbody>{s.cash.filter(c=>c.branch_id===branchId).map(c=><tr key={c.id}><td>{new Date(c.opened_at).toLocaleString('es-CO',{timeZone:'America/Bogota'})}</td><td>{cop(Number(c.opening))}</td><td><span className={`badge ${c.closed_at?'neutral':'green'}`}>{c.closed_at?'Cerrada':'Abierta'}</span></td><td>{c.expected===null?'—':cop(Number(c.expected))}</td><td>{c.counted===null?'—':cop(Number(c.counted))}</td><td>{c.closed_at?cop(Number(c.counted)-Number(c.expected)):'—'}</td></tr>)}</tbody></table></div></section>
   {w.manager&&<section className="panel space-top"><div className="panel-heading"><h2>Gastos de la sede</h2></div><div className="table-scroll"><table><thead><tr><th>Fecha</th><th>Categoría</th><th>Descripción</th><th>Valor</th></tr></thead><tbody>{s.expenses.filter(e=>e.branch_id===branchId).map(e=><tr key={e.id}><td>{day(e.created_at)}</td><td>{e.category}</td><td>{e.description}</td><td>{cop(Number(e.amount))}</td></tr>)}</tbody></table></div></section>}
  </>}
  {view==='reports'&&w.manager&&<>
   <div className="report-filters"><Field label="Desde"><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></Field><Field label="Hasta"><input type="date" value={to} min={from} onChange={e=>setTo(e.target.value)}/></Field><Field label="Sede"><select value={reportBranch} onChange={e=>setReportBranch(e.target.value)}><option value="all">Todas las sedes</option>{s.branches.filter(b=>b.tenant_id===branch?.tenant_id).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></Field><Field label="Trabajador"><select value={reportWorker} onChange={e=>setReportWorker(e.target.value)}><option value="all">Todo el equipo</option>{s.workers.filter(x=>x.tenant_id===branch?.tenant_id).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Servicio"><select value={reportService} onChange={e=>setReportService(e.target.value)}><option value="all">Todos</option>{s.catalog.filter(x=>x.tenant_id===branch?.tenant_id&&x.kind==='service').map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Medio de pago"><select value={reportMethod} onChange={e=>setReportMethod(e.target.value)}><option value="all">Todos</option><option value="cash">Efectivo</option><option value="transfer">Transferencia</option><option value="card">Datáfono</option></select></Field></div>
   <div className="warning subtle"><TriangleAlert size={16}/> Los dispositivos desconectados pueden tener registros pendientes. Los filtros seleccionan órdenes completas; los gastos se filtran solo por sede y fecha.</div><div className="metric-grid"><Metric label="Ventas" value={cop(reportSales)} detail={`${reportLive.length} órdenes sin anular`} icon={<CarFront size={18}/>}/><Metric label="Cobros" value={cop(reportPaid)} detail="Por fecha del pago" icon={<Wallet size={18}/>}/><Metric label="Gastos" value={cop(expenseTotal)} detail="Sedes y fechas seleccionadas" icon={<ReceiptText size={18}/>}/><Metric label="Flujo neto" value={cop(reportPaid-expenseTotal)} detail="Cobros menos gastos · no es utilidad" icon={<ChartNoAxesCombined size={18}/>} accent/></div><div className="section-toolbar"><p className="muted">Ticket promedio: <strong>{cop(reportLive.length?reportSales/reportLive.length:0)}</strong></p><button onClick={exportReport}><Download size={16}/> Exportar órdenes CSV</button></div>
   <section className="panel"><div className="panel-heading"><div><h2>Productividad del equipo</h2><p>Servicios terminados, ponderados por participación. No liquida comisiones.</p></div><button onClick={()=>downloadText('productividad.csv',csv([['Trabajador','Servicios atribuidos','Valor atribuido COP'],...productivity(reportOrders).map(p=>[p.name,p.services,p.value])]))}><Download size={16}/> CSV</button></div><div className="table-scroll"><table><thead><tr><th>Trabajador</th><th>Servicios atribuidos</th><th>Valor atribuido</th><th>Participación</th></tr></thead><tbody>{productivity(reportOrders).map((p,i)=><tr key={i}><td><strong>{p.name}</strong></td><td>{p.services.toFixed(2)}</td><td>{cop(p.value)}</td><td><div className="progress-track"><div style={{width:`${Math.min(100,reportSales?p.value/reportSales*100:0)}%`}}/></div></td></tr>)}</tbody></table></div></section>
  </>}
  {view==='settings'&&w.manager&&<><div className="section-toolbar"><p className="muted">Cada sede tiene su propia identidad y boleta.</p><div className="row-actions">{w.membership?.role==='owner'&&<><button onClick={invite}><Users size={16}/> Invitar usuario</button><button className="primary" onClick={()=>branchForm()}><Plus size={16}/> Nueva sede</button></>}</div></div><div className="settings-grid">{s.branches.filter(b=>b.tenant_id===branch?.tenant_id).map(b=><section className="panel branch-card" key={b.id}><div className="branch-icon">{b.logo?<img src={b.logo} alt={b.name}/>:<Building2 size={27}/>}</div><span className="badge neutral">{b.code}</span><h2>{b.name}</h2><p>NIT {b.nit||'sin configurar'}<br/>{b.address||'Dirección pendiente'}<br/>{b.phone}</p><blockquote>{b.footer}</blockquote><div className="row-actions"><button onClick={()=>branchForm(b)}>Personalizar</button>{b.id===branchId&&<label className="file-button">Subir logo<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)void run(()=>logo(file));}}/></label>}</div></section>)}</div><section className="panel space-top"><div className="panel-heading"><div><h2>Accesos del negocio</h2><p>Los lavadores se administran en Mi equipo; aquí aparecen usuarios con acceso.</p></div></div><div className="table-scroll"><table><thead><tr><th>Usuario</th><th>Rol</th><th>Sede</th></tr></thead><tbody>{s.memberships.filter(m=>m.tenant_id===branch?.tenant_id).map(m=><tr key={m.id}><td>{m.user_id===s.userId?'Tu cuenta':m.email||'Usuario invitado'}</td><td>{{owner:'Dueño',manager:'Administrador',cashier:'Cajero'}[m.role]}</td><td>{m.branch_id?s.branches.find(b=>b.id===m.branch_id)?.name:'Todas'}</td><td>{w.membership?.role==='owner'&&m.user_id!==s.userId&&<button className="danger" onClick={()=>form('Retirar acceso',[{name:'reason',label:'Motivo'}],async d=>{await w.action('membership.revoke',{id:m.id,reason:d.reason});})}>Retirar acceso</button>}</td></tr>)}</tbody></table></div></section></>}
  {view==='sync'&&<SyncCenter w={w}/>} 
  {view==='platform'&&s.platformAdmin&&<><div className="section-toolbar"><p className="muted">Alta de clientes y suscripciones cobradas por fuera de Brillo.</p><button className="primary" onClick={()=>form('Crear cliente',[{name:'name',label:'Nombre del negocio'},{name:'branch',label:'Nombre de la primera sede'},{name:'email',label:'Correo del dueño',type:'email'}],async d=>{const invited=await serverAction('/api/invitations',{email:d.email,role:'owner'});await serverAction('/api/platform',{action:'create',name:d.name,branch:d.branch,owner_id:invited.id});await w.refresh();})}><Plus size={16}/> Nuevo cliente</button></div><section className="panel table-scroll"><table><thead><tr><th>Cliente</th><th>Suscripción</th><th>Hasta</th><th/></tr></thead><tbody>{s.tenants.map(t=><tr key={t.id}><td>{t.name}</td><td>{t.subscription_status==='active'?'Activa':'Suspendida'}</td><td>{t.subscription_until??'Sin fecha'}</td><td><button onClick={()=>form('Actualizar suscripción',[{name:'status',label:'Estado',value:t.subscription_status,options:[{value:'active',label:'Activa'},{value:'suspended',label:'Suspendida'}]},{name:'until',label:'Pagada hasta',type:'date',value:t.subscription_until??'',required:false}],async d=>{await serverAction('/api/platform',{action:'subscription',id:t.id,status:d.status,until:d.until||null});await w.refresh();})}>Administrar</button></td></tr>)}</tbody></table></section></>}
  </main><footer className="app-footer"><span>brillo. <span>Tu lavadero, en orden.</span></span><span>Hecho para moverse contigo.</span></footer></div>
  {editor&&branch&&<Modal title={editor==='new'?'Nueva orden de servicio':`Editar ${editor.plate}`} wide onClose={()=>setEditor(null)}><OrderEditor existing={editor==='new'?undefined:editor} branch={branch} workers={workers.filter(w=>w.active)} catalog={catalog} device={w.device} onSave={async o=>{await w.saveOrder(o);setEditor(null);}}/></Modal>}
  {selectedCurrent&&<Modal title={`Orden · ${selectedCurrent.plate}`} wide onClose={()=>setSelected(null)}><div className="order-detail"><div className="detail-head"><div><small>{selectedCurrent.folio}</small><h3>{selectedCurrent.plate}</h3><p>{selectedCurrent.vehicle_type} · {selectedCurrent.customer_name||'Cliente ocasional'}</p></div><strong>{cop(total(selectedCurrent))}</strong></div>{selectedCurrent.lines.map((l,i)=><div className="detail-line" key={l.id}><div><strong>{l.name}</strong><small>{l.allocations.map(a=>`${a.name} (${a.percent}%)`).join(', ')}</small></div><span>{cop(l.price*l.quantity)}</span>{l.kind==='service'&&<select aria-label={`Estado ${l.name}`} value={l.status} disabled={selectedCurrent.cancelled} onChange={e=>void run(()=>w.saveOrder({...selectedCurrent,lines:selectedCurrent.lines.map((x,n)=>n===i?{...x,status:e.target.value as 'pending'|'working'|'done'}:x)}))}><option value="pending">Pendiente</option><option value="working">En proceso</option><option value="done">Terminado</option></select>}</div>)}{selectedCurrent.notes&&<p className="notice">{selectedCurrent.notes}</p>}<div className="row-actions wrap">{!selectedCurrent.payments.length&&!selectedCurrent.cancelled&&<button className="primary" onClick={()=>pay(selectedCurrent)}>Cobrar {cop(total(selectedCurrent))}</button>}{(!selectedCurrent.payments.length||w.manager)&&!selectedCurrent.cancelled&&<button onClick={()=>{setEditor(selectedCurrent);setSelected(null);}}>{selectedCurrent.payments.length?'Corregir orden':'Editar orden'}</button>}<button onClick={()=>{setReceipt(selectedCurrent);setSelected(null);}}><ReceiptText size={16}/> Ver boleta</button><button onClick={()=>void run(()=>share(selectedCurrent))}><Send size={16}/> WhatsApp</button><button onClick={()=>void run(()=>w.action('receipt.revoke',{order_id:selectedCurrent.id}))}>Revocar enlaces</button>{w.manager&&!selectedCurrent.cancelled&&<button className="danger" onClick={()=>form('Anular orden',[{name:'reason',label:'Motivo de anulación',type:'textarea'}],async d=>{await w.saveOrder({...selectedCurrent,cancelled:true,reason:d.reason});setSelected(null);})}>Anular</button>}</div></div></Modal>}
  {receipt&&<Modal title="Boleta de servicio" onClose={()=>setReceipt(null)}><Receipt order={receipt}/></Modal>}
  {dialog&&<Modal title={dialog.title} onClose={()=>setDialog(null)}><RecordForm fields={dialog.fields} onSubmit={dialog.save}/></Modal>}
 </div>;
}
function Metric({label,value,detail,icon,accent=false}:{label:string;value:string;detail:string;icon:ReactNode;accent?:boolean}){return <section className={`metric ${accent?'accent':''}`}><div className="metric-top"><span>{label}</span><span className="metric-icon">{icon}</span></div><strong>{value}</strong><p>{detail}</p></section>;}
