'use client';
import { Wallet, ReceiptText, CheckCheck } from 'lucide-react';
import { cop, day, scopeKey } from '@/lib/domain';
import { Metric } from './metric';
import type { WorkspaceViewModel } from './types';

export function CashView({ model }: { model: WorkspaceViewModel }) {
  const { w, s, branchId, collected, form } = model;
  return <>
   <div className="metric-grid three"><Metric label="Tu caja" value={w.cash?'Abierta':'Cerrada'} detail={w.cash?`Base ${cop(Number(w.cash.opening))}`:'Abre una caja para comenzar a cobrar'} icon={<Wallet size={19}/>} accent/><Metric label="Cobrado hoy" value={cop(collected)} detail="Todos los medios de pago" icon={<CheckCheck size={19}/>}/><Metric label="Gastos de hoy" value={cop(s.expenses.filter(e=>e.branch_id===branchId&&day(e.created_at)===day(new Date())).reduce((n,e)=>n+Number(e.amount),0))} detail="Gastos registrados de la sede" icon={<ReceiptText size={19}/>}/></div>
   <div className="section-toolbar"><p className="muted">Caja por operador y dispositivo. Los cierres requieren sincronizar primero.</p><div className="row-actions">{w.manager&&<button onClick={()=>form('Registrar gasto',[{name:'amount',label:'Valor (COP)',type:'number',min:0.01},{name:'category',label:'Categoría',options:['Insumos','Servicios públicos','Mantenimiento','Arriendo','Otros'].map(v=>({value:v,label:v}))},{name:'description',label:'Descripción'},{name:'method',label:'Medio de pago',options:[{value:'cash',label:'Efectivo de tu caja'},{value:'transfer',label:'Transferencia'},{value:'card',label:'Datáfono'}]}],async d=>{await w.action('expense.add',{...d,id:d._request_id,amount:Number(d.amount),cash_session_id:d.method==='cash'?w.cash?.id??null:null});})}>Registrar gasto</button>}{w.cash?<button className="primary" onClick={()=>form('Cerrar caja',[{name:'counted',label:'Efectivo contado (COP)',type:'number',min:0}],async d=>{if(w.operations.some(o=>o.scope===scopeKey(w.scope)))throw new Error('Sincroniza y resuelve los pendientes antes de cerrar caja');await w.action('cash.close',{id:w.cash!.id,counted:Number(d.counted)});})}>Cerrar caja</button>:<button className="primary" onClick={()=>form('Abrir caja',[{name:'opening',label:'Base inicial en efectivo (COP)',type:'number',value:0,min:0}],async d=>{await w.action('cash.open',{id:d._request_id,device_id:w.device,opening:Number(d.opening)});})}>Abrir caja</button>}</div></div>
   <section className="panel"><div className="panel-heading"><h2>Historial de cajas</h2></div><div className="table-scroll"><table><thead><tr><th>Apertura</th><th>Base</th><th>Estado</th><th>Esperado</th><th>Contado</th><th>Diferencia</th></tr></thead><tbody>{s.cash.filter(c=>c.branch_id===branchId).map(c=><tr key={c.id}><td>{new Date(c.opened_at).toLocaleString('es-CO',{timeZone:'America/Bogota'})}</td><td>{cop(Number(c.opening))}</td><td><span className={`badge ${c.closed_at?'neutral':'green'}`}>{c.closed_at?'Cerrada':'Abierta'}</span></td><td>{c.expected===null?'—':cop(Number(c.expected))}</td><td>{c.counted===null?'—':cop(Number(c.counted))}</td><td>{c.closed_at?cop(Number(c.counted)-Number(c.expected)):'—'}</td></tr>)}</tbody></table></div></section>
   {w.manager&&<section className="panel space-top"><div className="panel-heading"><h2>Gastos de la sede</h2></div><div className="table-scroll"><table><thead><tr><th>Fecha</th><th>Categoría</th><th>Descripción</th><th>Valor</th></tr></thead><tbody>{s.expenses.filter(e=>e.branch_id===branchId).map(e=><tr key={e.id}><td>{day(e.created_at)}</td><td>{e.category}</td><td>{e.description}</td><td>{cop(Number(e.amount))}</td></tr>)}</tbody></table></div></section>}
  </>;
}
