'use client';
import { CarFront, Users, Wallet, ArrowUpRight, ArrowRight, Clock, ChevronDown, ShieldCheck, ReceiptText } from 'lucide-react';
import { cop, total, status } from '@/lib/domain';
import { Metric } from './metric';
import type { WorkspaceViewModel } from './types';

export function OverviewView({ model }: { model: WorkspaceViewModel }) {
  const { w, today, live, sales, collected, workers, pending, orderTable, navigate } = model;
  return <>
   <div className="metric-grid"><Metric label="Ventas de hoy" value={cop(sales)} detail={`${live.length} órdenes registradas`} icon={<Wallet size={19}/>} accent/><Metric label="Vehículos atendidos" value={String(live.length).padStart(2,'0')} detail={`${live.filter(o=>status(o)==='Terminada').length} servicios terminados`} icon={<CarFront size={19}/>}/><Metric label="En el lavadero" value={String(live.filter(o=>status(o)!=='Terminada').length).padStart(2,'0')} detail="Órdenes pendientes y en proceso" icon={<Clock size={19}/>}/><Metric label="Por cobrar" value={cop(live.filter(o=>!o.payments.length).reduce((n,o)=>n+total(o),0))} detail={`${live.filter(o=>!o.payments.length).length} órdenes sin pago`} icon={<ReceiptText size={19}/>}/></div>
   <div className="overview-grid"><section className="panel activity-panel"><div className="panel-heading"><div><h2>Así va tu día</h2><p>Órdenes registradas por hora</p></div><span className="badge neutral">Hoy <ChevronDown size={12}/></span></div><div className="chart">{Array.from({length:12},(_,i)=>{const hour=i+7;const count=today.filter(o=>Number(new Intl.DateTimeFormat('en-GB',{timeZone:'America/Bogota',hour:'2-digit',hourCycle:'h23'}).format(new Date(o.created_at)))===hour).length;return <div className="chart-column" key={hour}><div className="bar-track"><div className={`bar ${count?'filled':''}`} style={{height:count?`${Math.max(15,Math.min(100,count*30))}%`:'3px'}}><span>{count||''}</span></div></div><small>{hour%12||12}{hour<12?'a':'p'}</small></div>;})}</div><div className="chart-footer"><span><i/> Órdenes de servicio</span><strong>{cop(collected)} <small>recaudados hoy</small></strong></div></section>
   <section className="panel team-panel"><div className="panel-heading"><div><h2>Tu equipo hoy</h2><p>El brillo es un trabajo en equipo</p></div><Users size={19}/></div>{workers.filter(x=>x.active).slice(0,4).map((worker,i)=>{const count=live.filter(o=>o.lines.some(l=>l.allocations.some(a=>a.worker_id===worker.id))).length;return <div className="team-row" key={worker.id}><span className={`avatar avatar-${i%3}`}>{worker.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><div><strong>{worker.name}</strong><small>{count} {count===1?'orden asignada':'órdenes asignadas'}</small></div><span className="active-dot"/></div>;})}{!workers.length&&<p className="muted">Agrega los trabajadores de esta sede.</p>}{w.manager&&<button className="text-button team-link" onClick={()=>navigate('team')}>Ver todo el equipo <ArrowRight size={15}/></button>}</section></div>
   <section className="panel"><div className="panel-heading"><div><h2>Órdenes recientes <span className="count-chip">{today.length}</span></h2><p>Los últimos vehículos que pasaron por aquí</p></div><button className="text-button" onClick={()=>navigate('orders')}>Ver todas <ArrowUpRight size={16}/></button></div>{orderTable(today.slice(0,5),true)}</section>
   <div className="bottom-note"><ShieldCheck size={15}/> {pending?`${pending} operaciones guardadas en este dispositivo, pendientes de sincronizar.`:w.demo?'Estás explorando datos de ejemplo.':'Los dispositivos sin conexión pueden tener registros aún no enviados.'}<span>{w.lastSync?`Actualizado ${new Date(w.lastSync).toLocaleTimeString('es-CO',{hour:'2-digit',minute:'2-digit'})}`:''}</span></div>
  </>;
}
